[workspace]
resolver = "3"
members = [
    "tsumugu-parser",
    "tsumugu-net",
    "tsumugu-cli"
]

[workspace.dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4.5", features = ["derive"] }
url = "2.5"
tracing = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["stream", "gzip", "deflate", "brotli", "socks", "rustls-tls-native-roots", "http2"] }
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tokio = { version = "1.4", features = ["rt-multi-thread"] }
http = "1.3"
