[package]
name = "tsumugu-net"
version = "0.20250929.1"
edition = "2021"
description = "Network abstraction for tsumugu"
license = "MIT"
repository = "https://github.com/taoky/tsumugu"

[dependencies]

anyhow = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

thiserror = "1.0.63"
http = "1"

[dev-dependencies]
test-log = { workspace= true }

[features]
with-impl = []
