[package]
name = "tsumugu-parser"
version = "0.20260424.0"
edition = "2024"
description = "Parser for various directory listing formats"
license = "MIT"
repository = "https://github.com/taoky/tsumugu"

[dependencies]
tsumugu-net = { version = "0", path = "../tsumugu-net" }

anyhow = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }

flate2 = "1.1"
apt-parser = "1.0"
percent-encoding = "2.3"
regex = "1.12"
scraper = "0.24"
thiserror = "2.0"

[dev-dependencies]
test-log = { workspace= true }
tsumugu-net = { path = "../tsumugu-net", features = ["with-impl"]}
