[package]
name = "tsumugu-parser"
version = "0.20250929.1"
edition = "2021"
description = "Parser for various directory listing formats"
license = "MIT"
repository = "https://github.com/taoky/tsumugu"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }

flate2 = "1.0.28"
apt-parser = "1.0.0"
percent-encoding = "2.3.1"
regex = "1.9.1"
thiserror = "1.0.63"
scraper = "0.23.1"

[dev-dependencies]
test-log = { workspace= true }
tokio = { workspace = true }
